name: Update Paladins - Champions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Component_update]
  schedule:
    - cron: '* */12 * * *'
jobs:
  update-champions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install httpx requests Pillow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get short SHA
      id: slug
      run: echo "{sha8}={$(echo ${GITHUB_SHA} | cut -c1-8)}" >> $GITHUB_OUTPUT

    - name: Updating Champions
      run: |
        cd .scripts
        python paladins_champs.py

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Update Paladins - Champions'
